#!/bin/bash
GITHASH=`git rev-parse --short HEAD`
echo "Current date:   `date`" >> VERSION.nek5000
echo "Current commit: $GITHASH" >> VERSION.nek5000
echo "Repository information:"  >> VERSION.nek5000
git remote show origin >> VERSION.nek5000
rm -f nek-$GITHASH.tar.gz
echo "Generating tarball from the latest Git commit: $GITHASH"
git archive --format=tar --prefix=nek/ HEAD > nek-$GITHASH.tar
tar -uf nek-$GITHASH.tar VERSION.nek5000
gzip nek-$GITHASH.tar
rm -f VERSION.nek5000
echo "The compressed tarball is nek-$GITHASH.tar.gz"
